include:
  - board: nice_nano_v2
    shield: cradio_left
    artifact-name: sweep_left_peripheral
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: cradio_left
    artifact-name: sweep_left_central
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  - board: nice_nano_v2
    shield: cradio_right
    artifact-name: sweep_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: cradio_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: sweep_dongle
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    artifact-name: settings_reset
    shield: settings_reset
