name: Build ZMK firmware
on:
  push:
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
      - 'build.yaml'
  pull_request:
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
      - 'build.yaml'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
