# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/includes/*.dtsi"
      - "tools/keymap-drawer/config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: tools/keymap-drawer/config.yaml
      output_folder: tools/keymap-drawer
      amend_commit: true
